// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    BaseHero: typeof import('./components/BaseHero.vue')['default']
    BaseSection: typeof import('./components/BaseSection.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    IconCheck: typeof import('./components/icon/IconCheck.vue')['default']
    IconMarketing: typeof import('./components/icon/IconMarketing.vue')['default']
    IntroductionBanner: typeof import('./components/IntroductionBanner.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    PricingSection: typeof import('./components/pricingSection/PricingSection.vue')['default']
    PricingSectionCard: typeof import('./components/pricingSection/PricingSectionCard.vue')['default']
    ProcessSection: typeof import('./components/processSection/ProcessSection.vue')['default']
    ProcessSectionCard: typeof import('./components/processSection/ProcessSectionCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    TeamSection: typeof import('./components/teamSection/TeamSection.vue')['default']
    TeamSectionCard: typeof import('./components/teamSection/TeamSectionCard.vue')['default']
  }
}
